/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PrincipalWidgetDashboard {
        "colors": string[];
        "labels": string[];
        "title": string;
        "values": string[];
    }
}
declare global {
    interface HTMLPrincipalWidgetDashboardElement extends Components.PrincipalWidgetDashboard, HTMLStencilElement {
    }
    var HTMLPrincipalWidgetDashboardElement: {
        prototype: HTMLPrincipalWidgetDashboardElement;
        new (): HTMLPrincipalWidgetDashboardElement;
    };
    interface HTMLElementTagNameMap {
        "principal-widget-dashboard": HTMLPrincipalWidgetDashboardElement;
    }
}
declare namespace LocalJSX {
    interface PrincipalWidgetDashboard {
        "colors"?: string[];
        "labels"?: string[];
        "onChangedDataset"?: (event: CustomEvent<any>) => void;
        "title"?: string;
        "values"?: string[];
    }
    interface IntrinsicElements {
        "principal-widget-dashboard": PrincipalWidgetDashboard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "principal-widget-dashboard": LocalJSX.PrincipalWidgetDashboard & JSXBase.HTMLAttributes<HTMLPrincipalWidgetDashboardElement>;
        }
    }
}
